NATPMP_REQUEST_FORMAT = "!BB"
NATPMP_RESPONSE_FORMAT = "!BBHI"
PORT_MAPPING_REQUEST_FORMAT = "!BBHHHI"
EXTERNAL_ADDRESS_RESPONSE_FORMAT = "!BBHII"
PORT_MAPPING_RESPONSE_FORMAT = "!BBHIHHI"
NATPMP_RESERVED_VALUE = 0
