class PacketParserErrorList:
    INVALID_PACKET = (0, 400, 'INVALID_INPUT_PACKET')
    INVALID_DHCP_PACKET = (1, 400, 'INVALID_DHCP_PACKET')
    INVALID_MDNS_PACKET = (2, 400, 'INVALID_MDNS_PACKET')
    INVALID_UPNP_PACKET = (3, 400, 'INVALID_UPNP_PACKET')

    DHCP_PACKET_PARSING_ERROR = (4, 500, 'FAILED_TO_PARSE_DHCP_PACKET')
    MDNS_UNPACKING_ERROR = (5, 400, 'FAILED_TO_UNPACK_MDNS_PACKET')
    SYN_PACKET_SIG_EXTRACTION_FAILED = (6, 500, 'SYN_PACKET_SIG_EXTRACTION_FAILED')

    INVALID_HTTP_NOTIFICATON_PACKET = (7, 500, 'INVALID_HTTP_NOTIFICATON_PACKET')
    UPNP_HTTP_REQUEST_PARSING_FAILED = (8, 500, 'UPNP_HTTP_REQUEST_PARSING_FAILED')
    UPNP_HTTP_RESPONSE_PARSING_FAILED = (9, 500, 'UPNP_HTTP_RESPONSE_PARSING_FAILED')
    UPNP_XML_PARSING_ERROR = (10, 500, 'UPNP_XML_PARSING_FAILED')


class PacketParserError(Exception):
    http_status = None
    code = None
    event_name = None
    message = None

    def __init__(self, error_type, message: str = None):
        self.message = message
        self.code, self.http_status, self.event_name = error_type
